# docker-compose.yml
version: '3.8'

services:
  chroma:
    image: chromadb/chroma:0.4.24
    container_name: chroma-db
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_data:/chroma/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
    driver: local